apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: bootnode-registrar-deployment
  labels:
    app: bootnode-registrar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootnode-registrar
  template:
    metadata:
      labels:
        app: bootnode-registrar
    spec:
      containers:
      - name: bootnode-registrar
        image: jpoon/bootnode-registrar:latest
        env:
        - name: BOOTNODE_SERVICE
          value: bootnode-service.default.svc.cluster.local
        ports:
        - containerPort: 9898
