apiVersion: v1
kind: Secret
metadata:
  name: genesis-file
type: Opaque
data:
  genesis.json: ewogICAgImNvbmZpZyI6IHsKICAgICAgICAiY2hhaW5JZCI6IDk4MDUyLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImVpcDE1MEJsb2NrIjogMCwKICAgICAgICAiZWlwMTU1QmxvY2siOiAwLAogICAgICAgICJlaXAxNThCbG9jayI6IDAKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDIwMDAwIiwKICAgICJnYXNMaW1pdCI6ICIweDQ5M0UwMCIsCiAgICAiYWxsb2MiOiB7CiAgICAgICAgImRhMWU1NTQ3MWRlZDAzYWRhZGVlNjNhYzY1OGI2NzEyNzdhNmM3ZDEiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfQogICAgfQp9Cgo=
