apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: geth-miner-deployment
  labels:
    app: geth-miner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geth-miner
  template:
    metadata:
      labels:
        app: geth-miner
    spec:
      containers:
      - name: geth-miner
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args: 
        - "-c"
        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --mine --minerthreads=1 --etherbase=0 --networkid=98052 --ethstats=$(HOSTNAME):$(WS_SECRET)@eth-stats-service.default"
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats-secret
              key: WS_SECRET
        ports:
        - name: discovery-udp
          containerPort: 30303
          protocol: UDP
        - name: discovery-tcp
          containerPort: 30303
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      initContainers:
      - name: init-genesis
        image: ethereum/client-go:v1.7.2
        args:
        - "init"
        - "/var/geth/genesis.json"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: genesis
          mountPath: /var/geth
      - name: create-account
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args:
        - "-c"
        - "printf '$(ACCOUNT_PASSWORD)\n$(ACCOUNT_PASSWORD)\n' | geth account new"
        env:
        - name: ACCOUNT_PASSWORD
          value: password
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      - name: get-bootnodes
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args:
        - "-c"
        - "apk add --no-cache curl && curl -v -o /root/.ethereum/bootnodes bootnode-registrar-service.default"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      volumes:
      - name: data
        emptyDir: {}
      - name: genesis
        secret:
          secretName: genesis-file