apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-miner-secret
  labels:
    app: {{ template "ethereum.name" . }}-geth-miner-secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # echo -n "very-secure-password" | base64
  accountsecret: dmVyeS1zZWN1cmUtcGFzc3dvcmQ=