apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-ethstats-secret
  labels:
    app: {{ template "ethereum.name" . }}-ethstats-secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # echo -n "azure\!123" | base64
  WS_SECRET: {{ .Values.ethstats.webSocketSecret }}